service: fg-slackbot-serverless

# frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x

functions:
  hello:
    handler: handler.alert
    events:
      - http: GET /
      - http: POST /